[package]
name = "librepo-comparator"
version = "0.1.0"
edition = "2021"

[lib]
name = "repo_comparator"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1"
rpmvercmp = "0.1.0"